version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      FLASK_ENV: development
    ports:
      - "8888:5000"
    depends_on:
      - db
      
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: questions
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"



volumes:
  postgres_data: